packages:
  - .
  - server

publicPackageEngineStrict: false

overrides:
  jiti: ^2.6.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@weapp-tailwindcss/merge-v3"
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - minidev
  - vue-demi
  - weapp-tailwindcss
